name: Continuous Delivery

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/continuous-delivery.yml
      - .yarn/**
      - src/**
      - .yarnrc.yml
      - Dockerfile
      - package.json
      - tsconfig.json
      - tsup.config.json
      - yarn.lock

jobs:
  push_to_registry:
    name: Push Docker image to container registry
    runs_on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/hblomqvist/discosino:latest
