name: Release

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.COMMIT_KEY }}
          release-type: node
          package-name: discosino
